# Generated by Django 4.1.3 on 2022-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_occuring_now', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('regarding', models.CharField(max_length=255)),
                ('crime_type', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
