# Generated by Django 4.1.3 on 2022-11-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('acknowledged', 'ACKNOWLEDGED')], default='pending', max_length=20),
        ),
    ]
