# Generated by Django 4.1.3 on 2022-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_created_at_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('acknowledged', 'ACKNOWLEDGED'), ('not acknowledged', 'NOT ACKNOWLEDGED')], default='pending', max_length=20),
        ),
    ]
